# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 494c1afe9b074bc627d0ad93bbb5be4fcf7e41821a9c905c4019ed26bff22737112027d3ef8587697ee563fca9907bf73035f82687fbb8c4199aa0230b9a815d

test:
  secret_key_base: aaaa796db3e18e93efa0ed4571eb43bbc77dd887bf30cf6ec7077539f54e9b33431ed641be7f228edc575dcf0148be799a564aa76f59dad646cf30092dd7abee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
